site_name: Spartan Write - User Guide
site_url: http://localhost:8000/

theme:
  name: shadcn

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.blocks.tab
  - pymdownx.superfences

extra_javascript:
  - js/tab-sync.js
